language: objective-c

osx_image: xcode8.2simfix

install: true

cache:
  directories:
    - $HOME/.cocoapods/

rvm:
  - 2.4.0

before_install:
- gem install cocoapods
- pod update

before_script:
- bundle install

notifications:
email:
  on_success: never

script:
- bundle exec fastlane test
