language: objective-c

osx_image: xcode7.3

install: true

cache:
  directories:
    - $HOME/.cocoapods/

rvm:
  - 2.4.0
  
before_script:
- bundle install
# - bundle exec pod repo update

notifications:
email:
  on_success: never

script:
- bundle exec fastlane test
